// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0
// source: query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getUser = `-- name: GetUser :one

SELECT id, username, fname, lname, email, salt, hash, city, nameforheader, phone, state, street, zip, license, paymentinfo, created_at, updated_at FROM users
WHERE id = $1
`

// These queries could and should be split over multiple files
// corresponding to each individual table in the db
// Users
func (q *Queries) GetUser(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Fname,
		&i.Lname,
		&i.Email,
		&i.Salt,
		&i.Hash,
		&i.City,
		&i.Nameforheader,
		&i.Phone,
		&i.State,
		&i.Street,
		&i.Zip,
		&i.License,
		&i.Paymentinfo,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
